version: "3"

services:
  front-end:
    build: frontend/
    ports:
      - "8080:80"
    environment:
      - RABBITMQ_USER=${USER}
      - RABBITMQ_PASS=${PASS}
    # uncomment for development
    volumes:
      - "./frontend/app:/var/www/html"
  messaging:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${USER}
      - RABBITMQ_DEFAULT_PASS=${PASS}
  backend:
    build: backend/
    environment: 
      - MSG_USER=${USER}
      - MSG_PASS=${PASS}
#  database:
#    image: mysql:8.0.20
#    volumes:
#      - db-data:/var/lib/mysql
#      - ./:/docker-entrypoint-initdb.d
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: cars
#      MYSQL_USER: user
#      MYSQL_PASSWORD: user