version: "3"

services:
  front-end:
    build: ../front-end/
    ports:
      - "8080:80"
    env_file:
      - ../front-end/.env
    environment:
      - RABBITMQ_USER=frontend
      - RABBITMQ_PASS=frontend
    # uncomment for development
    volumes:
      - "../front-end/app:/var/www/html"
  messaging:
    image: 'rabbitmq:3-management'
    environment:
      - RABBITMQ_DEFAULT_USER=messaging
      - RABBITMQ_DEFAULT_PASS=messaging
    ports:
      - 15672:15672
  backend:
    build: ./
#    env_file:
#     - ./backend/.env
    environment: 
      - NODE_ENV=development
      - MSG_USER=${MSG_USER}
      - MSG_PASS=${MSG_PASS}
      - DB_ROOT_USER=${DB_ROOT_USER}
      - DB_ROOT_PASS=${DB_ROOT_PASS}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_DATABASE=${DB_DATABASE}
  database:
    image: mysql:8.0.20
    volumes:
      - ../database/db-data:/var/lib/mysql
      - ../database/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cars
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser